### ISSUE TITLE
Reverse lookup fails when domain name is UTF-8

### ISSUE THREAD

**Issue by guyboertje** [logstash-plugins/logstash-filter-dns#22]
See [discuss post - Windows DNS incompatible character encodings](https://discuss.elastic.co/t/windows-dns-incompatible-character-encodings/48961)
See [Ruby issue - Resolv does not handle UTF8 domain names](https://bugs.ruby-lang.org/issues/4270).

TL;DR

When resolving domain names to IP addresses, if the domain name is an IDN e.g. `müller.com`, it needs to be converted to [Punycode](https://en.wikipedia.org/wiki/Punycode) first, e.g. xn--mller-kva.com

**Comment by BongoEADGC6** [comment]
Do you have a suggested workaround for this problem in the mean time?

**Comment by guyboertje** [comment]
@BongoEADGC6 
The only unfeasible suggestion would be to scrub your data for IDNs.

**Comment by BongoEADGC6** [comment]
I guess I could see of logstash can regex for it and not resolve the DNS of
it matches. Or pass it into ruby code to call the SimpleIDN gem for
manipulation.
