### ISSUE TITLE
Please add support for DNS suffix list

### ISSUE THREAD

**Issue by ThorbenJ** [logstash-plugins/logstash-filter-dns#32]
Please add the option to provide a list of suffixes to try and resolve with. i.e. If resolve fails, append each suffix in order until one succeeds, and fail if the list is exhausted.

> dns {
>   suffixes => ["domain1.com", "domain2.org"]
>   resolve => ["hostname1", "hostname2"] 
> }

Assuming hostname1 = bob and hostname2 = jim, tries:

returns first success:
- bob
- bob.domain1.com
- bob.domain2.org

returns first success
- jim
- jim.domain1.com
- jim.domain2.org

This would be very useful for Windows Eventlogs. They tend to contain unqualified hostnames, and suffixes can contain a list of known AD dns names.

Thank you & regards, -Thorben

**Comment by colinsurprenant** [comment]
Until #50 addresses this, note that it is possible to rely on `/etc/resolv.conf` per #55

**Comment by colinsurprenant** [comment]
#56 adds domain search list and is now available in v3.1.0.
