### ISSUE TITLE
Hit cache is synchronised, making concurrent lookups impossible

### ISSUE THREAD

**Issue by noofherder** [logstash-plugins/logstash-filter-dns#35]
Logstash version 5.5.1

Enabling the cache reduces dns performance, while a hacked version with no synchronisation has better performance.

Full details here: http://www.flax.co.uk/blog/2017/08/17/better-performance-logstash-dns-filter/

**Comment by ph** [comment]
By looking at the blog post, it make sense that you have better performance without the lock.
I need to take a look at the LRU implementation, the other that could be slow is the block creation on every request.

**Comment by andrewvc** [comment]
This should be fixed now that we use LRU::Redux for the cache

**Comment by andrewvc** [comment]
I misread this, reopening.

**Comment by jsvd** [comment]
this has been resolved with #42
