### ISSUE TITLE
Allow multiple nameservers

### ISSUE THREAD

**Issue by bradvido** [logstash-plugins/logstash-filter-dns#9]
Instead of only allowing a single custome nameserver, allow for multiple.

**Comment by dsvetlov** [comment]
I think it is better to setup local dns-server like dns-masq. It can cache
records and support two or even more dns resolvers.

чт, 25 июня 2015, 23:15, Brady Vidovic <notifications@github.com>:

> Instead of only allowing a single customer nameserver, allow for multiple.
> Query them sequentially, ending immediately on the first success.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logstash-plugins/logstash-filter-dns/issues/9>.
>
-- 

--
С уважением, Светлов Даниил.

**Comment by bradvido** [comment]
I don't think installing a local dns-masq instance along side every logstash instance is a feasible solution for most users.
